package com.local3dgs.capture

object UiText {
    const val APP_TITLE = "3DGS 采集"
    const val START_CAPTURE = "开始视频采集"
    const val STOP_CAPTURE = "停止视频采集"
    const val EXPORT_CAPTURE_BUNDLE = "导出采集包"
    const val OPEN_SETTINGS = "设置"
    const val SETTINGS_TITLE = "采集设置"
    const val SAVE_SETTINGS = "保存设置"
    const val SETTINGS_SAVED = "设置已保存"
    const val EXPORT_FAILED = "导出失败"
    const val SHARE_CAPTURE_BUNDLE = "分享采集包"
    const val CAPTURE_STARTED = "视频采集已开始"
    const val CAPTURE_STOPPED = "视频采集已停止"
    const val CAMERA_PERMISSION_REQUIRED = "需要相机权限"
    const val SETTING_RESOLUTION = "分辨率"
    const val SETTING_FPS = "帧率"
    const val SETTING_BITRATE = "码率"
    const val SETTING_FOCUS = "对焦"
    const val SETTING_STABILIZATION = "防抖"
    const val STATUS_READY = "准备就绪"
    const val STATUS_PREVIEW = "预览中"
    const val STATUS_RECORDING = "录制中"
}
